### ISSUE TITLE
tensorflow-rocm needs rebuild

### ISSUE THREAD

**Issue by nhermosilla-smbtc** [arch4edu/arch4edu#123]
I tried to install tensorflow and rocm, and I did so sucessfully. But as soon as I try to run anything from python, it fails mentioning libicuuc not found (version 68, latest on Arch repos is version 69).

**Comment by petronny** [comment]
When rebuilding this package, it will also say about missing libicuuc.so.68.
I think that some of its dependencies are the actual ones which need to rebuild.

Could you post more details about your error?
It may help me locating which dependencies need to rebuild.

**Comment by nhermosilla-smbtc** [comment]
I'd really like to help, but that's pretty much what it says:
```
Python 3.9.4 (default, Apr 20 2021, 15:51:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libicuuc.so.68: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/usr/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libicuuc.so.68: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
If there's something else I can do, please let me know.

**Comment by jusbw06** [comment]
just install `icu68` from the AUR, and it should work

**Comment by nhermosilla-smbtc** [comment]
> just install `icu68` from the AUR, and it should work

I tried that and had two issues:
1. The package icu68 fails to build unless I manually remove the "make check" step from the PKGBUILD (which according to the Gentoo wiki, is perfectly safe to do).
2. As soon as I try to import tensorflow in python, this happens:
`import tensorflow
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import keras
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/models.py", line 26, in <module>
    from tensorflow.python.keras.engine import functional
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 38, in <module>
    from tensorflow.python.keras.engine import training as training_lib
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 56, in <module>
    from tensorflow.python.keras.saving import hdf5_format
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 42, in <module>
    import h5py
  File "/usr/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
  File "h5py/_errors.pyx", line 1, in init h5py._errors
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
`

**Comment by nhermosilla-smbtc** [comment]
I finally got it working. It took me way too much to find the issue: I had numpy installed from the official repos (v1.20), but for some reason, I also had it installed with pip (v1.19). Python was picking the latter first, so it complained (correctly) because of the version disparity. So, to give this proper closure, installing icu68 (which now seems to work flawlessly, no hack or editing required as before), tensorflow loads as expected. Thanks @jusbw06 and @petronny for your help!

**Comment by nhermosilla-smbtc** [comment]
I finally got it working. It took me way too much to find the issue: I had numpy installed from the official repos (v1.20), but for some reason, I also had it installed with pip (v1.19). Python was picking the latter first, so it complained (correctly) because of the version disparity. So, to give this proper closure, installing icu68 (which now seems to work flawlessly, no hack or editing required as before), tensorflow loads as expected. Thanks @jusbw06 and @petronny for your help!
