### ISSUE TITLE
python-cupy cannot find libcudart.so.11.0

### ISSUE THREAD

**Issue by stefano-tronci** [arch4edu/arch4edu#220]
Hi! After installing `python-cupy` this happens in the python REPL when I try to import `cupy`:

```python
>>> import cupy as cp
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/usr/lib/python3.10/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/usr/lib/python3.10/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/usr/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 1, in init cupy.cuda.device
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
================================================================

```

` libcudart.so.11.0` does exist on my system:

```commandline
$ locate libcudart
/opt/cuda/targets/x86_64-linux/lib/libcudart.so
/opt/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
/opt/cuda/targets/x86_64-linux/lib/libcudart.so.11.8.89
/opt/cuda/targets/x86_64-linux/lib/libcudart_static.a
```

Could this be an issue with the package linking?

P.S.

Adding `/opt/cuda/targets/x86_64-linux/lib/` to `LD_LIBRARY_PATH` did not help.

**Comment by stefano-tronci** [comment]
Update: I built the package from [AUR](https://aur.archlinux.org/packages/python-cupy) and that imports fine.

**Comment by petronny** [comment]
Rebuilding cupy https://github.com/arch4edu/cactus/actions/runs/4314252005

Please give the rebuilt package a try when the build is finished.

**Comment by stefano-tronci** [comment]
Hi! The `python-cupy-11.6.0-2-x86_64.pkg.tar.zst` package from the pipeline import properly.

**Comment by petronny** [comment]
Great! And it's also published into the repository now.
