### ISSUE TITLE
mxnet import error due to libopenblas.so.0

### ISSUE THREAD

**Issue by hubutui** [arch4edu/arch4edu#23]
```
>>> import mxnet
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import mxnet
  File "/usr/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module
>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/lib/python3.7/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/usr/lib/python3.7/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenblas.so.0: 无法打开共享对象文件: 没有那个文件或目录
```
It works if I install `openblas-lapack` from arch4edu, but not `openblas` from community repo.

**Comment by petronny** [comment]
7abc681
