### ISSUE TITLE
Pyside2 build failed against Python 3.12

### ISSUE THREAD

**Issue by cybaol** [arch4edu/arch4edu#268]
The reason for the segment fault during compilation is that when running `generate_pyi.py`, a segment error occurs on line 271 when `import PySide2` is executed.

So I run` pip install PySide2 --break-system-packages`. Then debug with gdb shown in follow picture:

![Screenshot_select-area_20240428142913](https://github.com/arch4edu/arch4edu/assets/48387783/19adac0a-a52b-475d-b300-bbe19b032f5a)

This indicates that the program accessed an invalid memory address during execution, resulting in a segment error. Specifically, the error occurs in the PyDict_GetItem() function, which is used to get items from a Python dictionary. According to the information given, the function is called from the /usr/Lib/Libpython3.12.so library.

Segment errors are usually caused by accessing unallocated or freed memory. In this case, the incorrect memory access may have been caused by improper manipulation of the Python dictionary. To resolve this issue, you need to check the parts of the code related to dictionary manipulation and make sure that the indexes and keys of the dictionary are used correctly.

**Comment by cybaol** [comment]
Error log: https://github.com/arch4edu/cactus/actions/runs/8860200614

**Comment by petronny** [comment]
Detailed error log when building with `make VERBOSE=1 -j1`:
```
make[2]: Entering directory '/build/pyside2/src/build'
cd /build/pyside2/src/build/sources/pyside2/PySide2/QtCore && /usr/bin/cmake -E env LD_LIBRARY_PATH=/build/pyside2/src/build/sources/pyside2/libpyside:/build/pyside2/src/build/sources/shiboken2/libshiboken /usr/bin/python /build/pyside2/src/pyside-setup-opensource-src-5.15.13/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py QtCore --sys-path /build/pyside2/src/build/sources/pyside2 /build/pyside2/src/build/sources/shiboken2/shibokenmodule
Segmentation fault
make[2]: *** [sources/pyside2/PySide2/QtCore/CMakeFiles/QtCore_pyi.dir/build.make:70: sources/pyside2/PySide2/QtCore/CMakeFiles/QtCore_pyi] Error 1
make[2]: Leaving directory '/build/pyside2/src/build'
make[1]: *** [CMakeFiles/Makefile2:1573: sources/pyside2/PySide2/QtCore/CMakeFiles/QtCore_pyi.dir/all] Error 2
make[1]: Leaving directory '/build/pyside2/src/build'
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by petronny** [comment]
> The reason for the segment fault during compilation is that when running `generate_pyi.py`, a segment error occurs on line 271 when `import PySide2` is executed.

Looking into the `lib/python3.12/site-packages/PySide2/__init__.py` shows that the error is from `import shiboken2`. And `python -c 'import shiboken2'` also raises segmentation fault.

**Comment by petronny** [comment]
So the mininal environment to reproduce the error doesn't need to have neither pyside2 or shiboken2 installed.

You can just grab the compiled `libshiboken2.abi3.so.5.13` and `shiboken2.abi3.so` (these two are from pypi) and run `python -c 'import shiboken2'`.

**Comment by petronny** [comment]
Googling `python3.12 PyType_HasFeature` shows a related bug report, https://bugzilla.redhat.com/show_bug.cgi?id=2260160 .

It's mentioned that `Latest batch of updates to qt5 have resolved this issue`. Maybe it's `qt5` that needs to be fixed instead of Python 3.12.

**Comment by petronny** [comment]
Looks like `ros2-arch-deps` doesn't depend on `pyside2` anymore.

**Comment by petronny** [comment]
https://github.com/python/cpython/issues/118777 shows that the changes about `tp_dict` in Python 3.12 is related to this issue.
It will be NULL for static types and causing segmentation fault when accessing this pointer.

So I'm trying to make a patch like 
```
sed '108a\    if (dict == NULL) return 0;' -i $srcdir/$_pkgfqn/sources/shiboken2/libshiboken/signature/signature_helper.cpp
```
or
```
sed '108a\    if (dict == NULL) dict = PyType_GetDict(type);' -i $srcdir/$_pkgfqn/sources/shiboken2/libshiboken/signature/signature_helper.cpp
```
to solve this issue.

With one of the above patch applied, the segmentation fault is gone but new error occurs when running `generate_pyi.py`:
```
Traceback (most recent call last):
  File "/build/pyside2/src/pyside-setup-opensource-src-5.15.13/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 317, in <module>
    generate_all_pyi(outpath, options=options)
  File "/build/pyside2/src/pyside-setup-opensource-src-5.15.13/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 294, in generate_all_pyi
    generate_pyi(import_name, outpath, options)
  File "/build/pyside2/src/pyside-setup-opensource-src-5.15.13/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 220, in generate_pyi
    fmt = Formatter(outfile)
          ^^^^^^^^^^^^^^^^^^
  File "/build/pyside2/src/pyside-setup-opensource-src-5.15.13/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 119, in __init__
    typing.TypeVar.__repr__ = _typevar__repr__
    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot set '__repr__' attribute of immutable type 'typing.TypeVar'
make[2]: *** [sources/pyside2/PySide2/QtCore/CMakeFiles/QtCore_pyi.dir/build.make:70: sources/pyside2/PySide2/QtCore/CMakeFiles/QtCore_pyi] Error 1
make[1]: *** [CMakeFiles/Makefile2:1573: sources/pyside2/PySide2/QtCore/CMakeFiles/QtCore_pyi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by petronny** [comment]
The build will pass if we further remove the line `typing.TypeVar.__repr__ = _typevar__repr__`.
This will change the behavior of `__repr__` for some classes but maybe it's not important.

I'm going to update the pyside2 on AUR with my current efforts.

**Comment by Sir-Photch** [comment]
Many thanks for this!!!

**Comment by cybaol** [comment]
Thanks!!! But on my machine still failed.
![Screenshot_select-area_20240509175241](https://github.com/arch4edu/arch4edu/assets/48387783/c97eb88b-7aef-476b-aebc-7b0059a37edd)

**Comment by petronny** [comment]
> Thanks!!! But on my machine still failed.

Added a small fix. Should be buildable now.

**Comment by exstntlmsnthrp** [comment]
I've tried building twice, once prior to your fix and once after and both have failed. But, after digging further, the package I had with pyside2 listed as a dependency, was updated to Qt6 and no longer has this dependency; thus no longer causing a problem.

Regardless, the build failed and thought you may be interested.

**Comment by Sir-Photch** [comment]
I can confirm this builds fine :)

**Comment by petronny** [comment]
> I can confirm this builds fine after your fix, but further down, I get errors:

@Sir-Photch I can't find anything about `typing` so I guess the second patch that removing `__repr__` is irrelevant.

About the first patch you can try to rebuild with
```
sed '/PyObject \*dict = type->tp_dict;/a\    if (dict == NULL) return 0;' -i sources/shiboken2/libshiboken/signature/signature_helper.cpp
```
instead of the current one. May change some behaviour.

**Comment by exstntlmsnthrp** [comment]
> I can confirm this builds fine after your fix, but further down, I get errors: 
> ```
> qt.shiboken: (typesystem) /usr/include/qt/QtCore/qpluginloader.h:56: Unable to decide type of property: "loadHints" (QLibrary::LoadHints): Unable to translate type "QLibrary::LoadHints": Cannot find type entry for "QFlags<LoadHint>".
> ```
> among others. (This, for instance, is from the build of `qt_gui_cpp` needed by `rqt_graph` from ros2-iron.) Is it possible that this is another Python3.12 incompatibility, or related to the workaround that you made?
> 
> <details>
> <summary>Build output</summary>
> 
> ```
> --- stderr: qt_gui_cpp
> qt.shiboken: (typesystem) Duplicate type entry: 'QMessageLogContext'
> qt.shiboken: (typesystem) CLANG builtins includes directory: /usr/lib/clang/17/include
> (typesystem) clang_parseTranslationUnit2(0x0, cmd[28]=-isystem/usr/lib/clang/17/include -fPIC -Wno-constant-logical-operand -std=c++14 -I/home/chris/Source/ros2_ws/src/qt_gui_core/qt_gui_cpp/include -I/opt/ros/iron/include/pluginlib -I/opt/ros/iron/include/ament_index_cpp -I/opt/ros/iron/include/class_loader -I/opt/ros/iron/include/console_bridge_vendor -I/opt/ros/iron/include/rcpputils -I/opt/ros/iron/include/rcutils -I/usr/include -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/usr/include/PySide2 -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include /tmp/global_xzVMAs.hpp "-DQT_ANNOTATE_ACCESS_SPECIFIER(a)=__attribute__((annotate(#a)))" "-DQT_ANNOTATE_CLASS(type,...)=static_assert(sizeof(#__VA_ARGS__),#type);")
> qt.shiboken: (typesystem) /usr/include/qt/QtCore/qpluginloader.h:56: Unable to decide type of property: "loadHints" (QLibrary::LoadHints): Unable to translate type "QLibrary::LoadHints": Cannot find type entry for "QFlags<LoadHint>".
> qt.shiboken: (typesystem) /usr/include/qt/QtCore/qtypeinfo.h:255: Enum '(unnamed enum at /usr/include/qt/QtCore/qtypeinfo.h:255:1)' does not have a type entry
> qt.shiboken: (typesystem) /opt/ros/iron/include/rcutils/rcutils/logging.h:171: Enum 'RCUTILS_LOG_SEVERITY' does not have a type entry
> qt.shiboken: (typesystem) /usr/include/qt/QtGui/qopenglshaderprogram.h:179: While traversing QOpenGLShaderProgram: setAttributeArray(int,const float*,int,int): Cannot use parameter 2 as an array: <array> modification already applied.
> qt.shiboken: (typesystem) /usr/include/qt/QtWidgets/qaccessiblewidget.h:53: class 'QAccessibleWidget' inherits from unknown base class 'QAccessibleActionInterface'
> qt.shiboken: (typesystem) Duplicate type entry: 'QMessageLogContext'
> qt.shiboken: (typesystem) CLANG builtins includes directory: /usr/lib/clang/17/include
> (typesystem) clang_parseTranslationUnit2(0x0, cmd[28]=-isystem/usr/lib/clang/17/include -fPIC -Wno-constant-logical-operand -std=c++14 -I/home/chris/Source/ros2_ws/src/qt_gui_core/qt_gui_cpp/include -I/opt/ros/iron/include/pluginlib -I/opt/ros/iron/include/ament_index_cpp -I/opt/ros/iron/include/class_loader -I/opt/ros/iron/include/console_bridge_vendor -I/opt/ros/iron/include/rcpputils -I/opt/ros/iron/include/rcutils -I/usr/include -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/usr/include/PySide2 -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include /tmp/global_TBYFeP.hpp "-DQT_ANNOTATE_ACCESS_SPECIFIER(a)=__attribute__((annotate(#a)))" "-DQT_ANNOTATE_CLASS(type,...)=static_assert(sizeof(#__VA_ARGS__),#type);")
> qt.shiboken: (typesystem) /usr/include/qt/QtCore/qpluginloader.h:56: Unable to decide type of property: "loadHints" (QLibrary::LoadHints): Unable to translate type "QLibrary::LoadHints": Cannot find type entry for "QFlags<LoadHint>".
> qt.shiboken: (typesystem) /usr/include/qt/QtCore/qtypeinfo.h:255: Enum '(unnamed enum at /usr/include/qt/QtCore/qtypeinfo.h:255:1)' does not have a type entry
> qt.shiboken: (typesystem) /opt/ros/iron/include/rcutils/rcutils/logging.h:171: Enum 'RCUTILS_LOG_SEVERITY' does not have a type entry
> qt.shiboken: (typesystem) /usr/include/qt/QtGui/qopenglshaderprogram.h:179: While traversing QOpenGLShaderProgram: setAttributeArray(int,const float*,int,int): Cannot use parameter 2 as an array: <array> modification already applied.
> qt.shiboken: (typesystem) /usr/include/qt/QtWidgets/qaccessiblewidget.h:53: class 'QAccessibleWidget' inherits from unknown base class 'QAccessibleActionInterface'
> ---
> ```
> </details>

That's very similar to what I saw yesterday on my failed builds as well.

**Comment by Sir-Photch** [comment]
The behaviour changes, yes:

```
qt.shiboken: (typesystem) Duplicate type entry: 'QMessageLogContext'
qt.shiboken: (typesystem) CLANG builtins includes directory: /usr/lib/clang/17/include
(typesystem) clang_parseTranslationUnit2(0x0, cmd[28]=-isystem/usr/lib/clang/17/include -fPIC -Wno-constant-logical-operand -std=c++14 -I/home/chris/Source/ros2_ws/src/qt_gui_core/qt_gui_cpp/include -I/opt/ros/iron/include/pluginlib -I/opt/ros/iron/include/ament_index_cpp -I/opt/ros/iron/include/class_loader -I/opt/ros/iron/include/console_bridge_vendor -I/opt/ros/iron/include/rcpputils -I/opt/ros/iron/include/rcutils -I/usr/include -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/usr/include/PySide2 -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include /tmp/global_VLqnIx.hpp "-DQT_ANNOTATE_ACCESS_SPECIFIER(a)=__attribute__((annotate(#a)))" "-DQT_ANNOTATE_CLASS(type,...)=static_assert(sizeof(#__VA_ARGS__),#type);")
qt.shiboken: (typesystem) /usr/include/qt/QtCore/qpluginloader.h:56: Unable to decide type of property: "loadHints" (QLibrary::LoadHints): Unable to translate type "QLibrary::LoadHints": Cannot find type entry for "QFlags<LoadHint>".
qt.shiboken: (typesystem) /usr/include/qt/QtCore/qtypeinfo.h:255: Enum '(unnamed enum at /usr/include/qt/QtCore/qtypeinfo.h:255:1)' does not have a type entry
qt.shiboken: (typesystem) /opt/ros/iron/include/rcutils/rcutils/logging.h:171: Enum 'RCUTILS_LOG_SEVERITY' does not have a type entry
qt.shiboken: (typesystem) /usr/include/qt/QtGui/qopenglshaderprogram.h:179: While traversing QOpenGLShaderProgram: setAttributeArray(int,const float*,int,int): Cannot use parameter 2 as an array: <array> modification already applied.
qt.shiboken: (typesystem) /usr/include/qt/QtWidgets/qaccessiblewidget.h:53: class 'QAccessibleWidget' inherits from unknown base class 'QAccessibleActionInterface'
```

Albeit `rqt_graph` is still non-functional:

```
QVariant::load: unknown user type with name Qt::ToolBarArea.
Traceback (most recent call last):
  File "/home/chris/Source/ros2_ws/install/qt_gui/lib/python3.12/site-packages/qt_gui/main_window.py", line 120, in restore_state
    self._restore_state_from_perspective()
  File "/home/chris/Source/ros2_ws/install/qt_gui/lib/python3.12/site-packages/qt_gui/main_window.py", line 162, in _restore_state_from_perspective
    int(toolbar_settings.value(toolbar.objectName(), Qt.NoToolBarArea)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
fish: Job 1, 'LANG=en_US.UTF-8 rqt_graph' terminated by signal SIGABRT
```

Not sure though if this isn't an issue of rqt_graph itself.

**Comment by petronny** [comment]
> The build will pass if we further remove the line `typing.TypeVar.__repr__ = _typevar__repr__`. This will change the behavior of `__repr__` for some classes but maybe it's not important.

Adding `print(typing.__file__)` before this line shows that the `typing` module here is `/usr/lib/python3.12/typing.py`.
So I tried the following code under Python 3.12 and Python 3.11:
```
import typing

def _typevar__repr__(self):
    return "typing." + self.__name__

typing.TypeVar.__repr__ = _typevar__repr__
```
And the results show that only Python 3.12 raises `cannot set '__repr__' attribute of immutable type 'typing.TypeVar'`.

**Comment by petronny** [comment]
I find that `typing.TypeVar.__repr__ = _typevar__repr__` still exists in pyside6 at https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/shiboken6/shibokenmodule/files.dir/shibokensupport/signature/lib/pyi_generator.py?id=dc7b709f121a4489e2582eb8eabb0b22f82c2cca#n77.
And it shows:
```
# This is no longer necessary for modern typing versions.
# Ignore therefore if the repr is read-only and cannot be changed.
try:
    typing.TypeVar.__repr__ = _typevar__repr__
except TypeError:
    pass
```
So I think removing that line should be fine.

**Comment by Sir-Photch** [comment]
So if I understand you correctly, you are saying that these errors are not an issue of Pyside2?

**Comment by petronny** [comment]
The other patch that fixing the dict pointer may be not good enough.

This commit shows how it's fixed in pyside6. We may need to migrate all its content to pyside2.
https://code.qt.io/cgit/pyside/pyside-setup.git/commit/?id=441ffbd4fc622e67acd81e9c1c6d3a0b0fbcacf0

**Comment by petronny** [comment]
`grep tp_dict . -r | grep -v tp_dictoffset | grep -- -\>tp_dict | wc -l` shows that there is potentially 64 places that calls `->tp_dict` and may need to be fixed...

Maybe it's more easier to migrate things to pyside6...

**Comment by cybaol** [comment]
The process to migrate things to pyside6: https://github.com/ros-visualization/python_qt_binding/issues/141
