### ISSUE TITLE
No module named 'genmsg'

### ISSUE THREAD

**Issue by byteofsoren** [arch4edu/arch4edu#56]
Hi. Thank you for making such great work.
However, I have a problem while trying to install ROS related to genmsg.
```

:: Starting the build:
Running as unit: run-u4258.service
==> Making package: ros-melodic-std-srvs 1.11.2-2 (Sun 16 Feb 2020 22:22:06 CET)
==> Checking runtime dependencies...
error: could not register 'arch4edu' database (database already registered)
error: could not register 'arch4edu' database (database already registered)
error: could not register 'arch4edu' database (database already registered)
==> Checking buildtime dependencies...
error: could not register 'arch4edu' database (database already registered)
error: could not register 'arch4edu' database (database already registered)
error: could not register 'arch4edu' database (database already registered)
==> Retrieving sources...
  -> Downloading ros-melodic-std-srvs-1.11.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    206      0 --:--:-- --:--:-- --:--:--   205
100  2482    0  2482    0     0   1864      0 --:--:--  0:00:01 --:--:--  1864
==> Validating source files with sha256sums...
    ros-melodic-std-srvs-1.11.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting ros-melodic-std-srvs-1.11.2.tar.gz with bsdtar
==> Starting build()...
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.1")
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using default Python package layout
-- Found PY_em: /usr/lib/python3.8/site-packages/em.py
-- Using empy: /usr/lib/python3.8/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-3.8
-- catkin 0.7.19
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
/opt/ros/melodic/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <class 'ModuleNotFoundError'>: No module named 'genmsg'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/em.py", line 3303, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib/python3.8/site-packages/em.py", line 3301, in main
    invoke(sys.argv[1:])
  File "/usr/lib/python3.8/site-packages/em.py", line 3284, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/lib/python3.8/site-packages/em.py", line 2295, in wrap
    self.fail(e)
  File "/usr/lib/python3.8/site-packages/em.py", line 2284, in wrap
    callable(*args)
  File "/usr/lib/python3.8/site-packages/em.py", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/lib/python3.8/site-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3.8/site-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3.8/site-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3.8/site-packages/em.py", line 2596, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'genmsg'
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/catkin_generated/env_cached.sh
  "/usr/bin/python3" "/usr/lib/python3.8/site-packages/em.py" "--raw-errors"
  "-F"
  "/var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/cmake/std_srvs-genmsg-context.py"
  "-o"
  "/var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/cmake/std_srvs-genmsg.cmake"
  "/opt/ros/melodic/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  CMakeLists.txt:12 (generate_messages)


-- Configuring incomplete, errors occurred!
See also "/var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/CMakeFiles/CMakeOutput.log".
See also "/var/cache/private/pikaur/build/ros-melodic-std-srvs/src/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=4
Service runtime: 4.989s

Command 'systemd-run --pipe --wait -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/ros-melodic-std-srvs makepkg --force' failed to execute.
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
>
```
Do not know if it helps but trying to `import genmsg` have the following results.
```
Python 3.8.1 (default, Jan 22 2020, 06:38:00)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genmsg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'genmsg'
>>>
```
So then i chcked my pacma and:
```
arch4edu/ros-melodic-genmsg 0.5.12-1 [installed]
    ROS - Standalone Python library for generating ROS message and service data structures for various languages.
aur/ros-melodic-genmsg 0.5.12-1 [installed] (2, 0.94)
    ROS - Standalone Python library for generating ROS message and service data structures for various languages.
aur/ros-indigo-genmsg 0.5.7-1 (3, 0.00)
    ROS - Standalone Python library for generating ROS message and service data structures for various languages.
aur/ros-jade-genmsg 0.5.7-1 (1, 0.00)
    ROS - Standalone Python library for generating ROS message and service data structures for various languages.
aur/ros-lunar-genmsg 0.5.9-1 (2, 0.00)
    ROS - Standalone Python library for generating ROS message and service data structures for various languages.
aur/ros-kinetic-genmsg 0.5.11-1 (3, 0.00)
    ROS - Standalone Python library for generating ROS message and service data structures for various languages.

```
From that, I assume that it is a conflict where package helper pikaur installs two versions of the same programme and it's causing a conflict with itself.
Is that right? Is there any other way I could continue with the installation?

This question was also posted [here](https://answers.ros.org/question/344285/no-module-named-genmsg-during-ros-installation-in-aarchlinux/) for completeness.

**Comment by byteofsoren** [comment]
Got an update to ros-melodic-genmsg to day and that seamed to solve this problem.
