### ISSUE TITLE
roscore: No module named 'std_msgs'

### ISSUE THREAD

**Issue by byteofsoren** [arch4edu/arch4edu#58]
I'm on the tutorial of ros and tried to run the roscore when i got this problem.
`$ roscore`

```
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/roscore", line 72, in <module>
    import roslaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/__init__.py", line 62, in <module>
    from .scriptapi import ROSLaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/server.py", line 79, in <module>
    from rosgraph_msgs.msg import Log
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/__init__.py", line 2, in <module>
    from ._Log import *
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/_Log.py", line 8, in <module>
    import std_msgs.msg
ModuleNotFoundError: No module named 'std_msgs'

```
But I have the `ros-melodic-std-msgs` installed.
```

Searching... [###]
arch4edu/ros-melodic-std-msgs 0.5.12-1 [installed]
    ROS - Standard ROS Messages including common message types representing
    primitive data types and other basic message constructs, such as
    multiarrays.
aur/ros-melodic-std-msgs 0.5.12-1 [installed] (1, 0.00)
    ROS - Standard ROS Messages including common message types representing
    primitive data types and other basic message constructs, such as
    multiarrays.
aur/ros-indigo-std-msgs 0.5.10-1 (2, 0.00)
    ROS - Standard ROS Messages including common message types representing
    primitive data types and other basic message constructs, such as
    multiarrays.
aur/ros-jade-std-msgs 0.5.10-1 (1, 0.00)
    ROS - Standard ROS Messages including common message types representing
    primitive data types and other basic message constructs, such as
    multiarrays.
aur/ros-indigo-rocon-std-msgs 0.7.12-2 (0, 0.00)
    ROS - Standard messages used by other rocon specific package types.
aur/ros-kinetic-std-msgs 0.5.11-1 (3, 0.00)
    ROS - Standard ROS Messages including common message types representing
    primitive data types and other basic message constructs, such as
    multiarrays.
aur/ros-lunar-std-msgs 0.5.11-1 (2, 0.00)
    ROS - Standard ROS Messages including common message types representing
    primitive data types and other basic message constructs, such as
    multiarrays.
aur/ros-ardent-std-msgs 0.4.0-1 (0, 0.00)
    ROS - A package containing some standard message definitions.

```
What have I missed?

**Comment by byteofsoren** [comment]
That issue seamed to be solved with a newer version of the msgs packages that just arrived.
