### ISSUE TITLE
package name interference

### ISSUE THREAD

**Issue by chiboreache** [arch4edu/arch4edu#83]
package name should have prefix/postfix, not to be the same as pacman/aur repo's name

<img width="908" alt="Screenshot_20200617_090059" src="https://user-images.githubusercontent.com/16459251/84960000-388fed80-b109-11ea-8ff6-7a4091da2756.png">

**Comment by petronny** [comment]
Only PKGBUILDs maintained by arch4edu will have the special `prefix/postfix`.

Most packages in arch4edu should just be the binary for the AUR one.
And so are the rocm packages.

If you want to install the one from aur using `yay` for example, you can do
```
yay -S aur/rocm-dkms
```
And about the dependency issue, `rocm-dev` for example, you can do
```
yay -S aur/rocm-dkms aur/rocm-dev
```
to install all of them from AUR.

However, the rocm packages are broken on AUR.
```
yay -S aur/rocm-dkms aur/rocm-dev
```
will (or may) still raise errors if you build them in a clean chroot (or not).

So my suggestion is waiting for the fixes from the rocm-arch team.

**Comment by chiboreache** [comment]
pikaur really bad (and it's maintainer too) i'll trying yay now


```
↪ pikaur -S aur/caffe2
Reading repository package databases...
Reading local package database...
Traceback (most recent call last):
File "/usr/bin/pikaur", line 9, in <module>
main()
File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 435, in main
cli_entry_point()
File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 324, in cli_entry_point
run_with_sudo_loop(pikaur_operation)
File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 319, in run_with_sudo_loop
raise catched_exc  # pylint: disable=raising-bad-type
File "/usr/lib/python3.8/site-packages/pikaur/core.py", line 313, in run_with_sudo_loop
result = main_thread.get()
File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.8/site-packages/pikaur/main.py", line 135, in cli_install_packages
InstallPackagesCLI()
File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 161, in __init__
self.main_sequence()
File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 168, in main_sequence
self.get_all_packages_info()
File "/usr/lib/python3.8/site-packages/pikaur/install_cli.py", line 246, in get_all_packages_info
self.install_info = InstallInfoFetcher(
File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 67, in __init__
self.get_all_packages_info()
File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 164, in get_all_packages_info
self.get_aur_pkgs_info(self.not_found_repo_pkgs_names)
File "/usr/lib/python3.8/site-packages/pikaur/install_info_fetcher.py", line 374, in get_aur_pkgs_info
if aur_packages_names_to_versions[aur_pkg.name](aur_pkg.version):
KeyError
```
